### ISSUE TITLE
Drobne propozycje

### ISSUE THREAD

**Issue by dembanakh** [typsoon/Lost-in-The-Maze#1]
To są tylko bardzo drobne (nie zbyt ważne) propozycje. Nie musicie je stosować jeśli macie dobry powód, albo nawet jeśli wam po prostu nie podoba się 😃

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/globalClasses/enums/Direction.java#L6-L32
Żeby uniknąć tych switchów (które w zasadzie robią to samo), co myślicie o
```java
public enum Direction {
  LEFT(-1, 0), RIGHT(1, 0), UP(0, 1), DOWN(0, -1);

  private final int x, y;
  private Direction(int x, int y) { ... }
  
  next() { point.x += x; point.y += y; }
  getNext() { return new Point(point).next(); }
  ...
}
```

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/core/entities/Entity.java#L11
typo

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/core/entities/Minion.java#L43-L48
czy to nie powinno być `PlayerEnums.getMinionColor(owner)`?

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/core/boards/SquareBoard.java#L91-L94
`if (!mirrorMap.get(currentTunnel.getMirror()).add(direction)) break;`

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/core/boards/SquareBoard.java#L20
[EnumMap](https://docs.oracle.com/javase/8/docs/api/java/util/EnumMap.html)

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/core/tiles/Tile.java#L6
to jest mylące, bo np. `Wall` nie zwraca `null`

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/core/actionsHandlers/ActionHandlerFactory.java#L9-L17
```java
return switch (type)
        {
            case DOOR -> new DoorHandler(manager);
            case MOVE -> new MoveHandler(manager);
            case LASER -> new LaserHandler(manager);
            case SWORD -> new SwordHandler(manager);
            case MIRROR -> new MirrorHandler(manager);
        };
```

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/services/GameService.java#L12-L14
Dlaczego to nie jest po prostu `boolean`? Warto preferować typy prymitywne kiedy jest to możliwe

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/views/MainMenuSkin#L1-L15
Czy ten plik nie powinien być w `resources`?

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/views/gameScreen/LegalMoves.java#L49-L53
można też tak:
```java
try {
  return super.touchDown(...);
} finally {
  deactivateLegalMoves();
}
```

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/viewmodels/updates/updaters/Updater.java#L9-L15
Czy ma sens, żeby ta klasa była parametryzowana typem Updatu?
```java
class Updater<U> {
  abstract void update(U update);
  ...
}

class TileUpdateUpdater extends Updater<TileUpdate> { ... }
```

---

https://github.com/typsoon/Lost-in-The-Maze/blob/7d47c989aea5100bd4c21eafde8c53ecbde2f561/core/src/com/bksgames/game/core/main/GameManager.java#L22-L23
Dlaczego te metody są częścią interfejsu? wygląda, że są używane tylko wewnętrznie przez `SimpleGameManager`

**Comment by typsoon** [comment]
Dziękujemy za uwagi. Rozważyliśmy wszystkie i zastosowaliśmy większość. 🐨🐨🐨
