### ISSUE TITLE
Drobne propozycje

### ISSUE THREAD

**Issue by dembanakh** [typsoon/Lost-in-The-Maze#2]
To są tylko bardzo drobne (nie zbyt ważne) propozycje. Nie musicie je stosować jeśli macie dobry powód, albo nawet jeśli wam po prostu nie podoba się 😃

---

https://github.com/typsoon/Lost-in-The-Maze/blob/6344f77ae97e7384fce51cd86cb19f6ad79d9a45/core/src/com/bksgames/game/common/moves/Move.java#L10
ta linijka jest bardzo nieintuicyjna. Może raczej `position.copy()`?

---

https://github.com/typsoon/Lost-in-The-Maze/blob/532c8cf0c486f67caa7a184b905769d95526b4f4/core/src/com/bksgames/game/core/updates/SimpleTileUpdate.java#L15
czy jest jakiś powód dlaczego nie jest to `boolean`?

---

https://github.com/typsoon/Lost-in-The-Maze/blob/532c8cf0c486f67caa7a184b905769d95526b4f4/core/src/com/bksgames/game/core/tiles/Tile.java#L20-L22
nie może to być po prostu?
```java
if (this instanceof Tunnel tunnel) return tunnel;
return null;
```

---

https://github.com/typsoon/Lost-in-The-Maze/blob/532c8cf0c486f67caa7a184b905769d95526b4f4/core/src/com/bksgames/game/core/tiles/Tunnel.java#L41-L43
Z tego co widzę, ta metoda jest używana tylko raz, po prostu żeby przeiterować się po liście
Wtedy nie ma potrzeby kopiować `entities`

---

https://github.com/typsoon/Lost-in-The-Maze/blob/532c8cf0c486f67caa7a184b905769d95526b4f4/core/src/com/bksgames/game/core/main/DamageManager.java#L66-L69
bardzo długie są te linijki. Nie ma żadnego problemu z tym, aby cacheować w zmienną
```java
var tunnel = gameManager.getBoard().getTile(respawnable.getBaseSpawnPosition()).getTunnel();
```

---

https://github.com/typsoon/Lost-in-The-Maze/blob/532c8cf0c486f67caa7a184b905769d95526b4f4/core/src/com/bksgames/game/core/main/updateHolders/UpdateHolderFactory.java#L6-L8
Czy nie zadziałałaby tu jedna metoda zamiast pięciu? Coś w stylu
```java
Map<Class<? extends Update>, Function<? extends Update, UpdateHolder<? extends Update>>> constructors;
{
  constructors.put(TileUpdate.class, TileUpdateHolder::new);
}

static <U extends Update> UpdateHolder<U> produce(U update) {
    return constructors.get(update.getClass()).apply(update);
}
```
...Po tym jak napisałem ten kod, już nie wydaje się tak atrakcyjny. Ale może wam uda się jakoś to poprawić 🙃 

---

https://github.com/typsoon/Lost-in-The-Maze/blob/532c8cf0c486f67caa7a184b905769d95526b4f4/core/src/com/bksgames/game/services/SimpleGameService.java#L56-L58
`forwardUpdate` zawsze zwraca `true`. Czy w przyszłości jest przewidziana możliwość `false`? Bo inaczej nie ma powodu, żeby ta metoda nie była `void`

---

https://github.com/typsoon/Lost-in-The-Maze/blob/532c8cf0c486f67caa7a184b905769d95526b4f4/core/src/com/bksgames/game/viewmodels/SimpleViewModel.java#L53
`if (Objects.equals(minionPositions.get(i), start)) {}`

**Comment by mkdusia** [comment]
Dziękujemy bardzo za propozycje, przeanalizowaliśmy wszystkie i wdrożyliśmy część. Niektóre aspekty naszego kodu są przyszłościowe i dlatego na przykład na razie nie używamy boolean zwracanego w forwardUpdate. 
Jak chodzi o getTunnel to wynika to z chorobliwej niechęci @typsoon do instanceof 🙃
